# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    before_all do
        sh 'killall "Simulator" 2> /dev/null; xcrun simctl erase all'
        setup_jenkins
        clear_derived_data
        clean_build_artifacts

        sh 'bundle install --path .vendor/bundle'

        ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = '60'
        cocoapods
    end

    lane :build do 
        xcodebuild(
            scheme: "sampleprojectformobilesharedlibraryci",
            workspace: "sampleprojectformobilesharedlibraryci.xcworkspace",
            sdk: "iphonesimulator",
            buildlog_path: "./output/logs/"
        )
    end

    lane :unit_tests do
        scan(
            scheme: "sampleprojectformobilesharedlibraryci",
            workspace: "sampleprojectformobilesharedlibraryci.xcworkspace",
            output_files: "unit_tests_raport.xml",
            code_coverage: true,
            fail_build: false,
            sdk: "iphonesimulator",
            output_directory: "./output/logs/",
            buildlog_path: "./output/logs/"
        )
    end

    lane :swiftlint do
        swiftlint(
            mode: :lint,
            output_file: "swiftlint.result.xml",
            config_file: ".swiftlint.yml",
            ignore_exit_status: true,
            reporter: "checkstyle"
        )
    end

    lane :analyze do
        xcodebuild(
            scheme: "sampleprojectformobilesharedlibraryci",
            workspace: "sampleprojectformobilesharedlibraryci.xcworkspace",
            sdk: "iphonesimulator",
            buildlog_path: "./output/logs/",
            analyze: true
        )
    end

end
